# Ecommerce Sales Dashboard

## Notebook 02 – Data Cleaning

### Author
Divya Sesilia

### Project
End-to-End Data Analytics Project using SQL, Python, Excel, and Power BI

### Objective

The objective of this notebook is to clean and prepare the dataset for analysis.

### Tasks

- Load dataset
- Check data types
- Convert date columns
- Validate missing values
- Validate duplicate records
- Check numeric columns
- Save cleaned dataset

## Import Required Library

Pandas is used to manipulate and clean structured datasets.

In [24]:
import pandas as pd
import os

## Load Dataset


Load the raw dataset for cleaning.

In [22]:
df = pd.read_csv("../data/raw/superstore.csv")

# Display dataset dimensions
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (9994, 21)

## Check Data Types

In [8]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

## Convert Date Columns

The `Order Date` and `Ship Date` columns are currently stored as text (`object`).

To perform time-based analysis such as yearly, monthly, or quarterly sales trends, these columns must be converted to the `datetime` data type.

The dataset uses the **DD/MM/YYYY** date format, so `dayfirst=True` is used during conversion.

In [14]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    dayfirst=True
)

## Verify Data Types

In [15]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

## Check Missing Values

In [16]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

## Check Duplicate Records

In [17]:
df.duplicated().sum()

np.int64(0)

## Generate Descriptive Statistics

In [18]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

## Feature Engineering

Create additional columns that will be useful for time-based analysis.

In [19]:
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month_name()
df["Order Quarter"] = df["Order Date"].dt.quarter

## Preview Cleaned Dataset

In [20]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Quarter
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,November,4
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,November,4
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,June,2
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,October,4
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,October,4

## Export Cleaned Dataset

In [21]:
df.to_csv("../data/cleaned/superstore_cleaned.csv", index=False)

In [25]:
output_path = "../data/cleaned/superstore_cleaned.csv"

if os.path.exists(output_path):
    print("✅ Cleaned dataset saved successfully!")
    print(f"Location: {output_path}")
else:
    print("❌ File was not saved.")

✅ Cleaned dataset saved successfully!
Location: ../data/cleaned/superstore_cleaned.csv

# Conclusion

## Summary

- Successfully converted date columns to datetime.
- Verified data types.
- Confirmed there are no missing values.
- Confirmed there are no duplicate records.
- Created new time-based columns for analysis.
- Exported the cleaned dataset.

## Next Steps

The cleaned dataset is now ready for Exploratory Data Analysis (EDA).